# Generated by Django 3.1 on 2020-08-09 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 9, 15, 8, 30, 572002, tzinfo=utc)),
        ),
    ]
